### ISSUE TITLE
所有机器都可以直接打印

### ISSUE THREAD

**Issue by nisen** [osokay/Hello#6]
### 方案列表
*  每个机器安装驱动失败
*  wifi直连,失败
*  发fileServer, 打印  ------

**Comment by yahb5182** [comment]
* 下载打印机驱动并安装,安装过程中提示错误.   
  **错误内容:** *错误 出现严重错误,无法使用产品,单击"取消"以取消安装.*   
  换另一台电脑,多次安装均失败.
* 通过IP:192.168.223.1连接打印机,一直显示连接中.
